const test=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {Store}=require('../store'),{Service}=require('../service'),{AIManager}=require('../ai-manager'),{chooseMove}=require('../ai');
function setup(t){const store=new Store(':memory:');for(const id of ['human','other'])store.run('INSERT INTO users VALUES (?,?,?,?,?,?)',id,id,id,'hash','salt',Date.now());const service=new Service(store);service.connections.set('human',new Set([{res:{destroyed:true}}]));service.connections.set('other',new Set([{res:{destroyed:true}}]));t.after(()=>{service.aiManager?.close();store.close()});return {store,service,act(input){const r=store.roomFor('human');return service.action('human',{opId:crypto.randomUUID(),...input,...(r?{roomCode:r.code,gameId:r.game.id,version:r.version}:{})})}}}
async function until(fn){for(let n=0;n<200;n++){if(fn())return;await new Promise(r=>setTimeout(r,15))}assert.fail('AI timeout')}
for(const difficulty of ['easy','normal','hard'])test('AI wins first and blocks immediate threat: '+difficulty,()=>{let b=Array(225).fill(0);for(let c=0;c<4;c++)b[7*15+c]=1;assert.equal(chooseMove(b,1,difficulty),109);assert.equal(chooseMove(b,2,difficulty),109);b=Array(225).fill(0);for(let c=0;c<4;c++){b[7*15+c]=1;b[8*15+c]=2}assert.equal(chooseMove(b,2,difficulty),124)});
test('AI undo removes reply, preserves white opening, resign and restart archive without fake account',t=>{const f=setup(t);f.act({type:'create-ai',difficulty:'normal',color:'white'});let r=f.store.roomFor('human');assert.equal(r.humanColor,2);assert.throws(()=>f.act({type:'undo-ai'}));f.service.changed(()=>{f.service.place(r,7,7,1,'computer');f.store.saveRoom(r)});f.act({type:'move',row:7,col:8,ply:1});r=f.store.roomFor('human');f.service.changed(()=>{f.service.place(r,8,8,1,'computer');f.store.saveRoom(r)});f.act({type:'undo-ai'});assert.equal(f.store.roomFor('human').game.history.length,1);assert.equal(f.store.roomFor('human').game.history[0].color,1);f.act({type:'restart-ai',confirmed:true});assert.equal(f.service.history('human',1,'restart','ai').total,1);f.act({type:'resign',confirmed:true});assert.equal(f.service.history('human',1,'loss','ai').total,1);assert.equal(f.store.get('SELECT count(*) n FROM users').n,2);assert.equal(f.service.history('other').total,0);const id=f.service.history('human').items[0].id;assert.throws(()=>f.service.replay('other',id));assert.throws(()=>f.act({type:'undo-ai'}));assert.equal(f.service.history('human',1,'all','online').total,0)});
test('worker cancellation, offline hold, save failure and explicit retry',async t=>{const f=setup(t);const manager=new AIManager(f.service);f.service.aiManager=manager;f.act({type:'create-ai',difficulty:'hard',color:'black'});f.act({type:'move',row:7,col:7,ply:0});assert.equal(manager.jobs.size,1);f.act({type:'undo-ai'});assert.equal(manager.jobs.size,0);await new Promise(r=>setTimeout(r,70));assert.equal(f.store.roomFor('human').game.history.length,0);
 f.act({type:'move',row:7,col:7,ply:0});f.service.connections.delete('human');await until(()=>[...manager.jobs.values()][0]?.result!==undefined);assert.equal(f.store.roomFor('human').game.history.length,1);
 f.service.connections.set('human',new Set([{res:{destroyed:true}}]));f.store.db.exec("CREATE TRIGGER failure BEFORE UPDATE ON rooms BEGIN SELECT RAISE(ABORT,'failure'); END;");manager.sync();assert.equal(manager.errors.size,1);assert.equal(f.store.roomFor('human').game.history.length,1);f.store.db.exec('DROP TRIGGER failure');f.act({type:'retry-ai'});await until(()=>f.store.roomFor('human').game.history.length===2);
 const r=f.store.roomFor('human');f.act({type:'move',row:0,col:0,ply:r.game.history.length});f.act({type:'resign',confirmed:true});manager.sync();assert.equal(manager.jobs.size,0);await new Promise(r=>setTimeout(r,50));assert.equal(f.store.roomFor('human').phase,'ended');assert.equal(f.service.history('human').total,1)
});
test('AI restart rehydrates pending computer turn and account exclusivity',async t=>{const f=setup(t);f.act({type:'create-ai',difficulty:'easy',color:'white'});assert.throws(()=>f.act({type:'create'}));assert.throws(()=>f.act({type:'create-ai'}));const before=f.store.roomFor('human');const restored=new Service(f.store);restored.connections.set('human',new Set([{res:{destroyed:true}}]));const manager=new AIManager(restored);restored.aiManager=manager;t.after(()=>manager.close());manager.sync();await until(()=>f.store.roomFor('human').game.history.length===1);assert.equal(f.store.roomFor('human').game.id,before.game.id);assert.equal(restored.snapshot('human').players[0].status,'ai');assert.equal(f.store.get('SELECT count(*) n FROM users').n,2)});
